# Eve Horizon Fullstack Example - Manifest
# This manifest defines environments, components, and deployment configuration

name: fullstack-example
domain: fullstack.eve.local

defaults:
  env: staging
  execution: persistent
  harness: mclaude:fast
  worker_type: standard

# Container images for each component
# These are built from the Dockerfiles in apps/*/Dockerfile
components:
  db:
    image: postgres:16
    port: 5432
    replicas: 1
    env:
      POSTGRES_USER: eve
      POSTGRES_PASSWORD: eve
      POSTGRES_DB: eve

  api:
    image: eve-horizon-fullstack-example-api:local
    build:
      context: ./apps/api
      dockerfile: ./apps/api/Dockerfile
      target: production
    port: 3000
    replicas: 1
    env:
      NODE_ENV: production
      DATABASE_URL: postgres://eve:eve@test-db:5432/eve

  web:
    image: eve-horizon-fullstack-example-web:local
    build:
      context: ./apps/web
      dockerfile: ./apps/web/Dockerfile
    port: 80
    replicas: 1

# Database definition
databases:
  main:
    engine: postgres
    version: "16"

# Environment definitions
environments:
  test:
    type: persistent
    namespace: ehx-test
    db: main
    pipeline: deploy-test
    overrides:
      replicas: 1
      resources:
        memory: 256Mi
        cpu: 100m

  staging:
    type: persistent
    namespace: ehx-staging
    db: main
    pipeline: deploy-staging
    overrides:
      replicas: 1
      resources:
        memory: 512Mi
        cpu: 250m

  production:
    type: persistent
    namespace: ehx-prod
    db: main
    pipeline: deploy-production
    approval: required
    overrides:
      replicas: 2
      resources:
        memory: 1Gi
        cpu: 500m

tests:
  smoke:
    command: "./scripts/smoke-test.sh"

# Deterministic pipelines (Phase 2)
pipelines:
  deploy-test:
    actions:
      - type: build
      - type: release
      - type: deploy
      - type: run
        command_ref: smoke

  deploy-staging:
    actions:
      - type: build
      - type: release
      - type: deploy

  deploy-production:
    actions:
      - type: build
      - type: release
      - type: deploy
