# Eve Manifest
# Defines components, environments, and deployment pipelines

name: fullstack-example

# Optional: Override cluster's default domain for Ingress routing
# If not set, uses EVE_DEFAULT_DOMAIN from the cluster config
# domain: custom.example.com

# Container registry for pushing/pulling images
registry:
  host: ghcr.io
  namespace: incept5
  auth:
    username_secret: GHCR_USERNAME
    token_secret: GHCR_TOKEN

# Components to build and deploy
components:
  api:
    image: ghcr.io/incept5/eve-horizon-fullstack-example-api
    build:
      context: ./apps/api
      dockerfile: ./apps/api/Dockerfile
    port: 3000
    env:
      NODE_ENV: production
      DATABASE_URL: postgres://eve:${secret.POSTGRES_PASSWORD}@${ENV_NAME}-db:5432/eve
      EVE_JWKS_URL: ${EVE_JWKS_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: healthy
    api_spec:
      type: openapi
      spec_url: /openapi.json    # Fetched after deploy; defaults to /openapi.json for openapi type

  web:
    image: ghcr.io/incept5/eve-horizon-fullstack-example-web
    build:
      context: ./apps/web
      dockerfile: ./apps/web/Dockerfile
    port: 80
    depends_on:
      api:
        condition: healthy

  migrate:
    type: job
    image: postgres:16
    env:
      DATABASE_URL: postgres://eve:${secret.POSTGRES_PASSWORD}@${ENV_NAME}-db:5432/eve
    command: >-
      psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "CREATE TABLE IF NOT EXISTS notes (id serial primary key, body text);" -c "ALTER TABLE notes ENABLE ROW LEVEL SECURITY;"
    depends_on:
      db:
        condition: healthy

  db:
    type: database
    image: postgres:16
    port: 5432
    env:
      POSTGRES_USER: eve
      POSTGRES_PASSWORD: ${secret.POSTGRES_PASSWORD}
      POSTGRES_DB: eve
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eve"]
      interval: 5s
      timeout: 3s
      retries: 5

# Deployment environments
# Each environment is isolated with its own component instances.
# The db_ref references which database component DEFINITION to use (not a shared instance).
# For example, test environment gets "test-db", staging gets "staging-db", etc.
environments:
  test:
    pipeline: deploy-test
    db_ref: db                    # Uses db component definition → creates "test-db" instance
  staging:
    pipeline: deploy-staging
    db_ref: db                    # Uses db component definition → creates "staging-db" instance
  production:
    pipeline: deploy-production
    approval: required
    db_ref: db                    # Uses db component definition → creates "production-db" instance

# Test commands (referenced by pipelines)
tests:
  smoke:
    command: "./scripts/smoke-test.sh"

# Deterministic pipelines
pipelines:
  migrate:
    actions:
      - type: job
        service: migrate

  deploy-test:
    actions:
      - type: build
      - type: release
      - type: deploy
      - type: run
        command_ref: smoke

  deploy-staging:
    actions:
      - type: build
      - type: release
      - type: deploy

  deploy-production:
    actions:
      - type: build
      - type: release
      - type: deploy

  # Event-driven CI/CD pipelines
  ci-main:
    trigger:
      github:
        event: push
        branch: main
    steps:
      - name: build
        script:
          run: npm run build

      - name: test
        script:
          run: npm test
        depends_on:
          - build

      - name: deploy-staging
        script:
          run: eve deploy --env staging
        depends_on:
          - test

  ci-feature:
    trigger:
      github:
        event: push
        branch: feature/*
    steps:
      - name: lint
        script:
          run: npm run lint

      - name: test
        script:
          run: npm test

  remediation:
    trigger:
      system:
        event: job.failed
    steps:
      - name: analyze
        agent:
          prompt: "Analyze failure and propose a fix"
      - name: create-pr
        depends_on: [analyze]
        action:
          type: create-pr
          head: remediation/example
          base: main
          title: "Remediation"
          dry_run: true

# Workflows - Manual and scheduled operations
workflows:
  manual-deploy:
    manual: true
    db_access: read_write
    steps:
      - name: deploy
        script:
          run: eve deploy

  db-backup:
    manual: true
    db_access: read_only
    steps:
      - name: backup
        script:
          run: ./scripts/backup-db.sh
