# Eve Manifest
# Defines components, environments, and deployment pipelines

name: fullstack-example

# Optional: Override cluster's default domain for Ingress routing
# If not set, uses EVE_DEFAULT_DOMAIN from the cluster config
# domain: custom.example.com

# Container registry for pushing/pulling images
registry:
  host: ghcr.io
  namespace: incept5
  auth:
    username_secret: GHCR_USERNAME
    token_secret: GHCR_TOKEN

# Components to build and deploy
components:
  api:
    image: ghcr.io/incept5/eve-horizon-fullstack-example-api
    build:
      context: ./apps/api
      dockerfile: ./apps/api/Dockerfile
    port: 3000
    env:
      NODE_ENV: production
      DATABASE_URL: postgres://eve:${secret.POSTGRES_PASSWORD}@${ENV_NAME}-db:5432/eve
      EVE_JWKS_URL: ${EVE_JWKS_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: healthy
        migrations: true

  web:
    image: ghcr.io/incept5/eve-horizon-fullstack-example-web
    build:
      context: ./apps/web
      dockerfile: ./apps/web/Dockerfile
    port: 80
    depends_on:
      api:
        condition: healthy

  db:
    type: database
    image: postgres:16
    port: 5432
    env:
      POSTGRES_USER: eve
      POSTGRES_PASSWORD: ${secret.POSTGRES_PASSWORD}
      POSTGRES_DB: eve
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eve"]
      interval: 5s
      timeout: 3s
      retries: 5
    migrations:
      path: .eve/migrations
      on_deploy: true

# Deployment environments
environments:
  test:
    pipeline: deploy-test
    db_ref: db
  staging:
    pipeline: deploy-staging
    db_ref: db
  production:
    pipeline: deploy-production
    approval: required
    db_ref: db

apis:
  app:
    type: openapi
    base_url: http://api.examplee-test.lvh.me
    spec_url: http://test-api.eve-examplee-test.svc.cluster.local:3000/openapi.json
    auth: eve

# Test commands (referenced by pipelines)
tests:
  smoke:
    command: "./scripts/smoke-test.sh"

# Deterministic pipelines
pipelines:
  deploy-test:
    actions:
      - type: build
      - type: release
      - type: deploy
      - type: run
        command_ref: smoke

  deploy-staging:
    actions:
      - type: build
      - type: release
      - type: deploy

  deploy-production:
    actions:
      - type: build
      - type: release
      - type: deploy
