# Eve Manifest - v2 Compose Specification
# Defines services, environments, and deployment pipelines

schema: eve/compose/v1
project: fullstack-example

x-eve:
  agents:
    version: 1
    config_path: ./agents/agents.yaml
    teams_path: ./agents/teams.yaml
    profiles:
      primary-orchestrator:
        - harness: zai
          model: glm-4.7
          reasoning_effort: high
      primary-reviewer:
        - harness: zai
          model: glm-4.7
          reasoning_effort: medium
  chat:
    config_path: ./agents/chat.yaml
  packs:
    - source: ./packs/notes-ops

# Optional: Override cluster's default domain for Ingress routing
# If not set, uses EVE_DEFAULT_DOMAIN from the cluster config
# domain: custom.example.com

# Container registry for pushing/pulling images
registry:
  host: ghcr.io
  namespace: incept5
  auth:
    username_secret: GHCR_USERNAME
    token_secret: GHCR_TOKEN

# Services to build and deploy
services:
  api:
    image: ghcr.io/incept5/eve-horizon-fullstack-example-api
    build:
      context: ./apps/api
      dockerfile: ./apps/api/Dockerfile
    ports: [3000]
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://eve:${secret.POSTGRES_PASSWORD}@${ENV_NAME}-db:5432/eve
      EVE_JWKS_URL: ${EVE_JWKS_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    x-eve:
      api_spec:
        type: openapi
        spec_url: /openapi.json

  web:
    image: ghcr.io/incept5/eve-horizon-fullstack-example-web
    build:
      context: ./apps/web
      dockerfile: ./apps/web/Dockerfile
    ports: [80]
    depends_on:
      api:
        condition: service_healthy

  migrate:
    image: ghcr.io/incept5/eve-migrate:latest
    environment:
      DATABASE_URL: postgres://eve:${secret.POSTGRES_PASSWORD}@${ENV_NAME}-db:5432/eve
    depends_on:
      db:
        condition: service_healthy
    x-eve:
      role: job
      files:
        - source: db/migrations
          target: /migrations

  db:
    image: postgres:16
    ports: [5432]
    environment:
      POSTGRES_USER: eve
      POSTGRES_PASSWORD: ${secret.POSTGRES_PASSWORD}
      POSTGRES_DB: eve
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eve"]
      interval: 5s
      timeout: 3s
      retries: 5
    x-eve:
      role: database

# Deployment environments
environments:
  test:
    pipeline: deploy-test
  staging:
    pipeline: deploy-staging
  production:
    pipeline: deploy-production
    approval: required

# Deterministic pipelines
pipelines:
  migrate:
    steps:
      - name: run-migration
        action:
          type: job
          service: migrate

  deploy-test:
    steps:
      - name: build
        action: { type: build }
      - name: release
        depends_on: [build]
        action: { type: release }
      - name: deploy
        depends_on: [release]
        action: { type: deploy }
      - name: migrate
        depends_on: [deploy]
        action:
          type: job
          service: migrate
      - name: smoke-test
        depends_on: [migrate]
        script:
          run: ./scripts/smoke-test.sh
          timeout: 300

  deploy-staging:
    steps:
      - name: build
        action: { type: build }
      - name: release
        depends_on: [build]
        action: { type: release }
      - name: deploy
        depends_on: [release]
        action: { type: deploy }
      - name: migrate
        depends_on: [deploy]
        action:
          type: job
          service: migrate

  deploy-production:
    steps:
      - name: build
        action: { type: build }
      - name: release
        depends_on: [build]
        action: { type: release }
      - name: deploy
        depends_on: [release]
        action: { type: deploy }
      - name: migrate
        depends_on: [deploy]
        action:
          type: job
          service: migrate

  # Event-driven CI/CD pipelines
  ci-main:
    trigger:
      github:
        event: push
        branch: main
    steps:
      - name: build
        script:
          run: npm run build
      - name: test
        depends_on: [build]
        script:
          run: npm test
      - name: deploy-staging
        depends_on: [test]
        script:
          run: eve deploy --env staging

  ci-feature:
    trigger:
      github:
        event: push
        branch: feature/*
    steps:
      - name: lint
        script:
          run: npm run lint
      - name: test
        script:
          run: npm test

  remediation:
    trigger:
      system:
        event: job.failed
    steps:
      - name: analyze
        agent:
          prompt: "Analyze failure and propose a fix"
      - name: create-pr
        depends_on: [analyze]
        action:
          type: create-pr
          head: remediation/example
          base: main
          title: "Remediation"
          dry_run: true

# Workflows - Manual and scheduled operations
workflows:
  manual-deploy:
    manual: true
    db_access: read_write
    steps:
      - name: deploy
        script:
          run: eve deploy

  db-backup:
    manual: true
    db_access: read_only
    steps:
      - name: backup
        script:
          run: ./scripts/backup-db.sh
